{
  "formatVersion": "1.0",
  "component": {
    "url": "../../spek-dsl/2.0.11-rc.1/spek-dsl-2.0.11-rc.1.module",
    "group": "spek",
    "module": "spek-dsl",
    "version": "2.0.11-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.6",
      "buildId": "ppa5pw6ga5e2hdc55w6f5g2una"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "spek-dsl-jvm-2.0.11-rc.1.jar",
          "url": "spek-dsl-jvm-2.0.11-rc.1.jar",
          "size": 45205,
          "sha1": "70fee28804e198ec6ef33f4b65e13afb96ebea13",
          "md5": "798b4d6494f7fadf88ad5a776f2ecdff"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "spek-dsl-jvm-2.0.11-rc.1.jar",
          "url": "spek-dsl-jvm-2.0.11-rc.1.jar",
          "size": 45205,
          "sha1": "70fee28804e198ec6ef33f4b65e13afb96ebea13",
          "md5": "798b4d6494f7fadf88ad5a776f2ecdff"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../spek-dsl-metadata/2.0.11-rc.1/spek-dsl-metadata-2.0.11-rc.1.module",
        "group": "org.spekframework.spek2",
        "module": "spek-dsl-metadata",
        "version": "2.0.11-rc.1"
      }
    }
  ]
}
