{
  "formatVersion": "1.0",
  "component": {
    "url": "../../spek-dsl/2.0.11-rc.1/spek-dsl-2.0.11-rc.1.module",
    "group": "spek",
    "module": "spek-dsl",
    "version": "2.0.11-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.6",
      "buildId": "ppa5pw6ga5e2hdc55w6f5g2una"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "spek-dsl-js-2.0.11-rc.1.jar",
          "url": "spek-dsl-js-2.0.11-rc.1.jar",
          "size": 17804,
          "sha1": "50097d0392870dbb88b8422953798e2c377a4e74",
          "md5": "cce5ba6ca3d278c783295389666a3b12"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "spek-dsl-js-2.0.11-rc.1.jar",
          "url": "spek-dsl-js-2.0.11-rc.1.jar",
          "size": 17804,
          "sha1": "50097d0392870dbb88b8422953798e2c377a4e74",
          "md5": "cce5ba6ca3d278c783295389666a3b12"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../spek-dsl-metadata/2.0.11-rc.1/spek-dsl-metadata-2.0.11-rc.1.module",
        "group": "org.spekframework.spek2",
        "module": "spek-dsl-metadata",
        "version": "2.0.11-rc.1"
      }
    }
  ]
}
