{
  "formatVersion": "1.0",
  "component": {
    "url": "../../spek-dsl-native-macos/2.0.11-rc.1/spek-dsl-native-macos-2.0.11-rc.1.module",
    "group": "org.spekframework.spek2",
    "module": "spek-dsl-native-macos",
    "version": "2.0.11-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.6",
      "buildId": "ppa5pw6ga5e2hdc55w6f5g2una"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "spek-dsl-metadata-2.0.11-rc.1.jar",
          "url": "spek-dsl-metadata-2.0.11-rc.1.jar",
          "size": 17629,
          "sha1": "d6724762eb63d6d96db1e5ed5c729c401c2c409a",
          "md5": "3cdc92bcb70eb0033f6f074b9bfec974"
        }
      ]
    }
  ]
}
