{
  "formatVersion": "1.0",
  "component": {
    "group": "org.spekframework.spek2",
    "module": "spek-runner-junit5",
    "version": "2.0.11-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.6",
      "buildId": "ppa5pw6ga5e2hdc55w6f5g2una"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "spek-runner-junit5-2.0.11-rc.1.jar",
          "url": "spek-runner-junit5-2.0.11-rc.1.jar",
          "size": 24220,
          "sha1": "44b043db30a79124fd946b0304e95c7427bf3ba1",
          "md5": "2bef1b9699fdcb1fb448e21d6305f05a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "spek",
          "module": "spek-runtime",
          "version": {
            "requires": "2.0.11-rc.1"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "spek-runner-junit5-2.0.11-rc.1.jar",
          "url": "spek-runner-junit5-2.0.11-rc.1.jar",
          "size": 24220,
          "sha1": "44b043db30a79124fd946b0304e95c7427bf3ba1",
          "md5": "2bef1b9699fdcb1fb448e21d6305f05a"
        }
      ]
    }
  ]
}
