{
  "formatVersion": "1.0",
  "component": {
    "url": "../../spek-runtime/2.0.11-rc.1/spek-runtime-2.0.11-rc.1.module",
    "group": "spek",
    "module": "spek-runtime",
    "version": "2.0.11-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.6",
      "buildId": "ppa5pw6ga5e2hdc55w6f5g2una"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "spek",
          "module": "spek-dsl",
          "version": {
            "requires": "2.0.11-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "spek-runtime-jvm-2.0.11-rc.1.jar",
          "url": "spek-runtime-jvm-2.0.11-rc.1.jar",
          "size": 153659,
          "sha1": "f37de5919b29418a32c7a0ba2f48865c3eb34aef",
          "md5": "aac303f4675cfa2c75e99453de361d8d"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "spek",
          "module": "spek-dsl",
          "version": {
            "requires": "2.0.11-rc.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "io.github.classgraph",
          "module": "classgraph",
          "version": {
            "requires": "4.8.37"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "spek-runtime-jvm-2.0.11-rc.1.jar",
          "url": "spek-runtime-jvm-2.0.11-rc.1.jar",
          "size": 153659,
          "sha1": "f37de5919b29418a32c7a0ba2f48865c3eb34aef",
          "md5": "aac303f4675cfa2c75e99453de361d8d"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../spek-runtime-metadata/2.0.11-rc.1/spek-runtime-metadata-2.0.11-rc.1.module",
        "group": "org.spekframework.spek2",
        "module": "spek-runtime-metadata",
        "version": "2.0.11-rc.1"
      }
    }
  ]
}
