{
  "formatVersion": "1.0",
  "component": {
    "url": "../../spek-runtime-native-macos/2.0.11-rc.1/spek-runtime-native-macos-2.0.11-rc.1.module",
    "group": "org.spekframework.spek2",
    "module": "spek-runtime-native-macos",
    "version": "2.0.11-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.6",
      "buildId": "ppa5pw6ga5e2hdc55w6f5g2una"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "spek",
          "module": "spek-dsl",
          "version": {
            "requires": "2.0.11-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "spek-runtime-metadata-2.0.11-rc.1.jar",
          "url": "spek-runtime-metadata-2.0.11-rc.1.jar",
          "size": 24336,
          "sha1": "87346e7155fb86f5be212e9757e1508b99c968f8",
          "md5": "ffdc69f61026e719a5a27f1f2f91ce83"
        }
      ]
    }
  ]
}
