{
  "formatVersion": "1.0",
  "component": {
    "url": "../../spek-dsl/2.0.11-rc.1/spek-dsl-2.0.11-rc.1.module",
    "group": "spek",
    "module": "spek-dsl",
    "version": "2.0.11-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.6",
      "buildId": "ppa5pw6ga5e2hdc55w6f5g2una"
    }
  },
  "variants": [
    {
      "name": "macos-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "spek-dsl.klib",
          "url": "spek-dsl-native-macos-2.0.11-rc.1.klib",
          "size": 51983,
          "sha1": "106aa45a388f65bdc10da7b465266eaaa3a7e8",
          "md5": "db7e20ef9f2461e011416da17b925f2f"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../spek-dsl-metadata/2.0.11-rc.1/spek-dsl-metadata-2.0.11-rc.1.module",
        "group": "org.spekframework.spek2",
        "module": "spek-dsl-metadata",
        "version": "2.0.11-rc.1"
      }
    }
  ]
}
